from transformers import pipeline
import pandas as pd

pipe = pipeline("text-classification", model="nlptown/bert-base-multilingual-uncased-sentiment")

input = "Hello there! How can I assist you today?"

res = pipe(input)
for item in res:
    value = item['label']
    if value == '1 stars' or value == '2 stars':
        out = 0
    elif value == '3 stars' or value == '4 stars' or value == '5 stars':
        out = 1
if out == 0:
    result = 'The Given text has been generated by Human'
else:
    result = 'The text has been generated by an AI'
print(result)
