from flask import Flask, jsonify, request
from flask_cors import CORS
from transformers import pipeline
import pandas as pd


app = Flask(__name__)
CORS(app)

def detect_text(text):
        pipe = pipeline("text-classification", model="nlptown/bert-base-multilingual-uncased-sentiment")
        res = pipe(text)
        for item in res:
            value = item['label']
            if value == '1 stars' or value == '2 stars':
                out = 0
            elif value == '3 stars' or value == '4 stars' or value == '5 stars':
                out = 1
        if out == 0:
            result = 'The Given text has been generated by Human'
        else:
            result = 'The Given text has been generated by an AI'
        return result

@app.route("/api/add", methods=['POST'])
def add_numbers():
    try:
        data = request.get_json()
        result1 = data.get('numA')
        result = detect_text(result1)
        print(result)

        return jsonify({'result': result})
    
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == "__main__":
    app.run(debug=True, port=8080)
